### ISSUE TITLE
Sync failed from both devices

### ISSUE THREAD

**Issue by michaelGregoire** [freecinc/freecinc-issues#12]
Trying to sync my tasks and it's suddenly failing with the following message: "Cannot perform this action while handshake is in progress. Sync failed. Could not connect to the Taskserver."

**Comment by michaelGregoire** [comment]
Not sure if you did something, or the issue worked itself out, but I was able to sync again. Closing this ticket.

**Comment by djmitche** [comment]
taskd crashes on some kinds of data, and it takes a while to restart.  I suspect that's what happened here.  With luck, the incidence of such crashes does not increase with the 2.6.0 release, but that remains to be seen.
