### ISSUE TITLE
Freecinc Error 503

### ISSUE THREAD

**Issue by felixschurk** [freecinc/freecinc-issues#13]
Hei, first of all thanks for the great service.
Since yesterday I think the FreeCinc Server is down and the website also throws an 503 Error.
Kind Regards Felix

**Comment by djmitche** [comment]
Sorry about this!  I also use freecinc so I'm missing sync functionality too :)

I suspect this began when the Digitalocean "automatic" Kubernetes upgrade occurred.

**Comment by djmitche** [comment]
Looks like it -- I ultimately added a new node pool and deleted the old.  It's back up now.

Sorry again :(

**Comment by felixschurk** [comment]
No worries. 
Thank you alot. :)
