### ISSUE TITLE
[question] why is this service free

### ISSUE THREAD

**Issue by louis-morgan** [freecinc/freecinc-issues#16]
Thanks so much for this service it's a life saver. I'm not massively clued up on how the task server works but I'm curious as to why this is free and how long it will remain working.

If I wanted to have my own server, what is the actual server and where is it?

I'm trying to understand how all this works

Thank you for your time!

**Comment by djmitche** [comment]
Well, it's not free for me :)  I use it, and it costs about $35/mo.  I accept [sponsorships](https://github.com/sponsors/djmitche) to defray that cost.

I don't know how long it will keep working -- probably roughly as long as I am still using it, and as long as it's still useful to other people.  I inherited the service from someone else, and if I stop using it I will try to find another person to run the services.  But, there are are no sure things in life, right?

The server behind this is `taskd` - the source is [here](https://github.com/GothenburgBitFactory/taskserver).  You can see how it's all put together the some other repositories in this organization.  Lots of people do run their own servers, such as on a VPS or a home server.
