### ISSUE TITLE
Syncing fails and times out after 40 seconds

### ISSUE THREAD

**Issue by woltersdylan** [freecinc/freecinc-issues#17]
Just started using this service to sync after attempting to deal with TaskServers frustrating documentation slideshow thing - everything has been exceptional until today where the service now fails to sync. 

The following error occurs exactly 40 seconds after initiating the sync:
```
Failed to receive header: Cannot perform this action while handshake is in progress.
Sync failed.  Could not connect to the Taskserver.
```

I'm not sure if this is a client problem or a server one, but I figured I'd report it just in case.

**Comment by woltersdylan** [comment]
Syncing is working again! I'm assuming this was just an instance of poor timing for my sync! Closing this.

**Comment by djmitche** [comment]
The taskd server is single-threaded, so this sometimes occurs when another very long sync operation is occurring -- for example when the server can't find a common ancestor for a very long task history.
