### ISSUE TITLE
Service may be down

### ISSUE THREAD

**Issue by trev-dev** [freecinc/freecinc-issues#18]
"Syncing with freecinc.com:53589

Failed to receive header: Cannot perform this action while handshake is in progress.
Sync failed.  Could not connect to the Taskserver."

**Comment by djmitche** [comment]
This seems to happen from time to time.  I think taskd has a memory leak, and when it gets too large it slows down for a while before k8s restarts it.  It seems to be working now -- can you confirm?

**Comment by trev-dev** [comment]
Thanks, this is good to know!  I can indeed sync once again.  Closing this issue :)
