### ISSUE TITLE
Monthly Maintenance - Oct 2022

### ISSUE THREAD

**Issue by djmitche** [freecinc/freecinc-issues#19]
* [x] Add an issue in https://github.com/freecinc/freecinc-issues
* [x] df on each data volume
* [x] Upgrade k8s cluster version (automatic?)
* [x] Upgrade nodes (automatic?)
* [ ] Upgrade Helm locally, re-run helm upgrade
* [ ] Upgrade cert-manager (installed with helm)
* [ ] Upgrade nginx-ingress (patched in manually)

This hasn't been done lately, and k8s has been force-upgraded to 1.22, which broke the old nginx-ingress.

**Comment by djmitche** [comment]
```
/dev/disk/by-id/scsi-0DO_Volume_pvc-b0d47808-6c3f-48b7-9951-fc3865b6855a  9.8G  1.3G  8.0G  14% /taskddata
/dev/disk/by-id/scsi-0DO_Volume_pvc-68d5c16b-d2d8-4374-9d95-06112df585de  974M  259M  648M  29% /pki
```

**Comment by djmitche** [comment]
inodes are up from 31% in 2020 to 61%:
```
/dev/disk/by-id/scsi-0DO_Volume_pvc-b0d47808-6c3f-48b7-9951-fc3865b6855a   640K   36K  605K    6% /taskddata
/dev/disk/by-id/scsi-0DO_Volume_pvc-68d5c16b-d2d8-4374-9d95-06112df585de    64K   39K   26K   61% /pki
```
probably deleting a bunch of old stuff there would help.  I'm not sure how to tell what's still in use?

**Comment by djmitche** [comment]
Helm upgraded to 3.10.0 via Ansible

**Comment by djmitche** [comment]
Uuuuggh what a q@#%#!^

Kubernetes can DIAF.

**Comment by djmitche** [comment]
So I'm out of time to work on this now.  But, my `task sync` is also broken some I'm motivated to fix this.

I will likely get rid of all the k8s nonsense and just configure this on a VM somewhere.  It's not like k8s has been more reliable than a single VM.

**Comment by trev-dev** [comment]
Sorry this is turning into a big pain!  Thanks for your efforts so far.

**Comment by djmitche** [comment]
I have a start on setting this up on GKE.  It will probably be more expensive, but GKE does offer managed certificates (so, no cert-manager) and a built-in ingress (so, no nginx-ingress).  So that's nice.

**Comment by djmitche** [comment]
What appears to be impossible on GKE is to both terminate TLS in some kind of nice thing that will manage certs for me (an Ingress) _and_ terminate a TCP connection for taskd (which requires a LoadBalancer).

I think I'll settle for just not using TLS for the http part (the website).  If anyone has a better idea, I'm happy to share admin of this site!

**Comment by djmitche** [comment]
OK, it's back up, [much simplified](https://github.com/freecinc/freecinc-helm/commit/4ce4a0dbe7c7de4261832830ae9601e4d072fd12).

It no longer supports TLS for the website.  I'll open a new ticket to remove support for issuing new keys, and we'll just keep this working for existing users with no new users -- until either someone comes along who can host this better than I can, or until I finally get around to integrating taskchampion and we build a new backend.
