### ISSUE TITLE
FreeCinc closing

### ISSUE THREAD

**Issue by djmitche** [freecinc/freecinc-issues#20]
It's time to shut down freecinc.

 * The `taskd` server is not built for production deployments -- it's really only suitable for one person running it on a server under their desk.  It crashes, hangs, leaks memory, is horrendously insecure, and has no diagnostic output.
 * The service is expensive to operate (~US$40/mo).
 * My Kubernetes skills are not sufficient to keep it running (witness the https portion of the website being down).

I'll be turning off the service in January 2023.

**Comment by hickey** [comment]
Perfectly understandable. 

I have seen over the past couple of days issues with connecting to freecinc.com and just found your message. I would like to take the opportunity to thank you for providing the service out there early on when I started using Taskwarrior. It was quite useful to have a `taskd` server out there to keep all my machines in sync.

**Comment by djmitche** [comment]
Thanks!  I do wish I could continue supporting this, but it's just not practical..

**Comment by djmitche** [comment]
There are still a number of users of this service, and I'm concerned the news may not have reached them.  There aren't a lot of avenues for TW news, but we did miss one: `taskwarrior.org`.

I'm adding an announcement to `taskwarrior.org` about this, and pushing the date back by one month.

**Comment by djmitche** [comment]
[announcement](https://github.com/GothenburgBitFactory/tw.org/pull/482)

**Comment by traycerb** [comment]
Yes, thank  you also 🙏.  I was (still am 😰) using it.   Where is the best resource for setting up your own taskserver?  The [official docs ](https://taskwarrior.org/docs/taskserver/setup/) show an empty page.  I seem to recall freecinc had good instructions, at least for configuring things on the user side.  Perhaps you can post how you set it up here for posterity's sake, seeing how freecinc is down.  

EDIT: Well, I'm answering my own questions but taskd setup has moved to this page https://gothenburgbitfactory.github.io/taskserver-setup/ (regrettably as a slide show).

**Comment by djmitche** [comment]
It's definitely not easy to set up!  That slideshow is the only documentation I know of, and is what I followed when I set up my own server.

**Comment by hickey** [comment]
I have been working on getting the `taskd` and `web` repackaged in Docker containers. That work is happening over in https://gitlab.com/wt0f/freecinc-taskd and https://gitlab.com/wt0f/freecinc-web. The original `Dockerfiles` were not building for me and the base images were quite old. I suspect that there were updates to the base images that conflicted with what was being done in the `Dockerfile`s. 

The plan is to get good solid Docker images and produce a good process for initializing the certs and required data structures. It will have to get done one way or another :-)

Things have been slowed down quite a bit by my move across country, but I am staring to have some free time again and will continue working on getting the containers built and operational.

**Comment by djmitche** [comment]
It looks like those are baed on https://github.com/freecinc/freecinc-web and https://github.com/freecinc/freecinc-taskd?  You're also welcome to https://github.com/freecinc/freecinc-helm!  In fact, I'd be happy to collaborate on getting things back up and running, if you've got the know-how.

If you're just looking to get a docker container that will run taskd, suitable for individual use (so, without freecinc-web), that might be an easier task.

**Comment by hickey** [comment]
Yes, they are direct copies of your repos for the baseline. Initially i was hoping it would be just a `docker build` to get images, but there were issues with the build and it seemed that every little change I would do to try to get the build going cause another problem. So that is when I decided that I would fork the repos and do a major update to pretty recent images and modules. 

It is mostly a time issue right now. Getting everything running will not really be a problem. I actually started working on `taskd` yesterday while the girlfriend was at the doctor for her foot. Sure enough by the time I really got working on the project she came out. 

The first version will be enough to where I can get it running for my uses. Then I will work on getting the image  to where anybody with a bit of knowledge (i.e. can execute the proper commands) can properly setup the certs and server config. At that point I can focus on the web component for anyone who wants to run the web interface. Just have not fully decided if I am going to keep them as 2 separate images or try to combine them into one image. 

Certainly I would welcome help. I don't see this as terribly complex task. Certainly not compared to a lot of other things I work on.

**Comment by djmitche** [comment]
It's probably not worth someone setting up their own freecinc-web, so perhaps the best course is to continue with the freecinc-taskd image (maybe just renaming it to `taskwarrior-taskd`?) and set that up so that it can generate creds via a command-line setup.

**Comment by clach04** [comment]
> Yes, thank you also 🙏. I was (still am 😰) using it. Where is the best resource for setting up your own taskserver? The [official docs ](https://taskwarrior.org/docs/taskserver/setup/) show an empty page. I seem to recall freecinc had good instructions, at least for configuring things on the user side. Perhaps you can post how you set it up here for posterity's sake, seeing how freecinc is down.
> 
> EDIT: Well, I'm answering my own questions but taskd setup has moved to this page https://gothenburgbitfactory.github.io/taskserver-setup/ (regrettably as a slide show).

https://github.com/GothenburgBitFactory/guides/tree/master/taskserver-setup has a tex version 

and https://github.com/GothenburgBitFactory/taskserver-setup appears to be the source version

**Comment by hickey** [comment]
I have just released the `1.1.0` version of the `taskd` docker container that I had announced a while back. This release simplifies a bunch of the nitty gritty of getting `taskd` up and running. There was also a bit of work added to create users and their certificates. 

I have changed the project name also so not to infringe as much on the Freecinc name/reputation. While the link above should work for quite a while, the new `taskd` project is https://gitlab.com/wt0f/taskd/. The README has (I think) everything one needs to know to get the server up and running. If there are any problems encountered please drop an issue into the project to let me know.

As for freecinc-web, I have done no work on anything there. Right now I am not planning on it and won't be planning anything unless I receive a bunch of requests or when I finally get some time to dig through the code that is there. If the code is really just the Freecinc website that assisted a user with setting up Taskwarrior to sync with Freecinc, then I agree with @djmitche that there probably is not much value there. My initial thought with freecinc-web was it would be wonderful to have a self-service portal for people to create a user and manage their certs. I suspect that this functionality would be all new code and most of what is there would go away.

**Comment by djmitche** [comment]
Thanks!  This looks fantastic, and will be a great help to folks in migrating away from freecinc!

**Comment by djmitche** [comment]
Oh, and to be clear -- I don't mind "infringement" on the name or anything like that (and to my knowledge it's not a trademark).  I only suggested renaming the image to avoid confusion with `freecinc.com`, which as a globally unique domain name can only run one taskd. :)

**Comment by hickey** [comment]
I spent the last day or so considering changing the name away from Freecinc to avoid confusion and there was really nothing in the container that was (for lack of a better term) "Freecinc". It is really just a `taskd` install and I did not want to upset anyone (mostly you) by using the Freecinc name. When I saw your posting from 2 weeks ago suggesting a name change I decided to go ahead and pull the trigger now before people start looking at the previous name. :smile:

BTW, I just looked at www.freecinc.com and the page is still allowing people to generate keys. You may consider updating the page to let anyone coming across the page know that the service will be shutting down and the date of expected shutdown. You are more than welcome to point people to my repo to setup their own `taskd` server.

**Comment by djmitche** [comment]
Huh, I can't load it.

I wonder if that has to do with HSTS -- it automatically defaults to https for me.  What browser are you using?  I wonder if it's in the HSTS preload list for some browsers and not others.

**Comment by djmitche** [comment]
Oh, interesting!  It seems to be cached in my browser session, but bleeding even into private tabs. Opening it in a new Firefox profile works OK (well, images don't load, but what can you do).  I'll update it.

**Comment by hickey** [comment]
I have tried in Firefox and Chrome. Both of them show the same page.

**Comment by djmitche** [comment]
Yeah, I think if you had accessed freecinc.com when it had its http -> https redirect in place, your browser would "remember" that redirect and you'd see the same behavior I do.

**Comment by djmitche** [comment]
Website is updated:

![image](https://user-images.githubusercontent.com/28673/214991738-c8b216c7-c9cf-4524-957b-cddf5e0be744.png)

(images and CSS still don't load since they use https URLs, but at least the information is there)

**Comment by suchoudh** [comment]
You tried and thank you for that. 

Love the sentiment.

 Hope in a near future (someone will find )  a better solution can emerge which can address financial and technical burnout.

**Comment by WinterStar2** [comment]
Discovered the announcement yesterday and switched to my own LAN Docker set-up, so I'm off the FreeCinc server as well.
Wanted to say thanks for the wonderful service you have provided over the years!

**Comment by djmitche** [comment]
Today's the day!  I've shut down the k8s cluster, and I'm deleting the Google Cloud project.

I'll hang onto the DNS for a year or two, in case it's useful.

**Comment by cedricwider** [comment]
Thank you so much for having provided this service :heart: 
You have no idea how much I loved using it.

**Comment by kirkster96** [comment]
In order to help those looking for another solution, I made a tutorial for how to deploy taskd on your own Azure VM:

https://youtu.be/6Ci_JyvVIaI

**Comment by smeester** [comment]
Hi, I was using it in the past as well. Only found out today the service was stopped (when I tried to sync after a long time :) ). Thanks for hosting it. Reading the discussion above, quite understandable you had to kill it.

**Comment by djmitche** [comment]
Thanks for the kind words!

**Comment by kenthorvath** [comment]
**Inthe.AM** provides a free `taskd` service. More details [here](https://inthe.am/).

**Features:**

- **Built-In Taskserver**: Sync with your local Taskwarrior client.
- **E-mail**: Add tasks via a whitelist-controlled email address.
- **RSS Feeds**: View tasks in any RSS reader.
- **Trello**: Use Taskwarrior tasks with Trello boards.
- **iCal Feed**: See tasks in Google Calendar.
- **SMS**: Add tasks via SMS using Twilio.
- **Mobile Web UI**: Optimized for mobile and desktop. Web-app mode available for iPhone users.
- **Open Source**: Built on open-source. Feature requests and suggestions can be made [here](https://github.com/coddingtonbear/inthe.am/issues?page=1&state=open).
- **RESTful API**: Manage tasks with the provided API.

**Comment by MabudAlam** [comment]
> **Inthe.AM** provides a free `taskd` service. More details [here](https://inthe.am/).
> 
> **Features:**
> 
> * **Built-In Taskserver**: Sync with your local Taskwarrior client.
> * **E-mail**: Add tasks via a whitelist-controlled email address.
> * **RSS Feeds**: View tasks in any RSS reader.
> * **Trello**: Use Taskwarrior tasks with Trello boards.
> * **iCal Feed**: See tasks in Google Calendar.
> * **SMS**: Add tasks via SMS using Twilio.
> * **Mobile Web UI**: Optimized for mobile and desktop. Web-app mode available for iPhone users.
> * **Open Source**: Built on open-source. Feature requests and suggestions can be made [here](https://github.com/coddingtonbear/inthe.am/issues?page=1&state=open).
> * **RESTful API**: Manage tasks with the provided API.

Now, inthe.am is also shutting down their service.

**Comment by sergiorgiraldo** [comment]
I moved to a self-hosted server, wrote a list of the commands I used to make it work on a Azure VM:

https://github.com/sergiorgiraldo/taskserver/blob/1.2.0/__HOWTO.md

**Comment by zArubaru** [comment]
This seems like an alternative also, haven't given it a try (yet!):
https://wingtask.com

**Comment by plum** [comment]
> This seems like an alternative also, haven't given it a try (yet!): https://wingtask.com

Works well. Very easy to install (1 minute!)  I've decided to go with this solution.
