### ISSUE TITLE
Bad CERT file. The requested data were not available

### ISSUE THREAD

**Issue by cjadeveloper** [freecinc/freecinc-issues#8]
I am on Ubuntu WSL with version 2.5.1 of taskwarrior. I have the certificates, keys and everything is fine until I do `task sync init`. There I get the error: **"Bad cert file. The requested data were not available."**

I've port 53589 open on Windows

I send some screenshots

![image](https://user-images.githubusercontent.com/2917217/81004317-964ecb80-8e22-11ea-82c7-6d135c19cefa.png)

![image](https://user-images.githubusercontent.com/2917217/81004348-a49ce780-8e22-11ea-85c0-14e314592a66.png)

![image](https://user-images.githubusercontent.com/2917217/81004611-08bfab80-8e23-11ea-8a52-e4f56e37e0c2.png)

Any idea?

**Comment by djmitche** [comment]
Did this work once, and has stopped, or is this the first time trying?

**Comment by cjadeveloper** [comment]
First time

**Comment by djmitche** [comment]
Hm, that is suggesting that there's no cert file matching freecinc_17c1e409.cert.pem on the server.  I don't know why that would be the case!  I did just go through the setup process on freecinc.com, and it worked fine, so perhaps the easiest thing to do is to try again?

**Comment by djmitche** [comment]
Did you figure it out?
