### ISSUE TITLE
Freecinc is down

### ISSUE THREAD

**Issue by carlsverre** [freecinc/freecinc-issues#9]
Seems like it's down.  Another GKE issue?

**Comment by carlsverre** [comment]
Oh it looks like you switched to DO.  Bummer - hopefully it's something simple.

**Comment by djmitche** [comment]
Indeed, I'm having a look now..

**Comment by djmitche** [comment]
```
 Unable to attach or mount volumes: unmounted volumes=[pki taskddata], unattached volumes=[pki secrets default-token-dlbzv taskddata]: timed out waiting for the condition 
```

**Comment by djmitche** [comment]
And it looks like that pod is un-deletable :(

**Comment by djmitche** [comment]
It looks like this might have been a DO automatic node update that exploded.

**Comment by djmitche** [comment]
It's back up.  I'll keep poking until that last node is fixed.

**Comment by djmitche** [comment]
ugh, now I'm getting
```
Sync failed.  The Taskserver returned error: 504 Request too big
```
which is probably reasonable having been down for 16 hours

**Comment by djmitche** [comment]
..but means I need to manually sync un-sync'd tasks and make a new freecinc account.

taskd really is awful

**Comment by ploth** [comment]
set this
```
# /var/taskd/config
                                                                                                        
request.limit 0 
```

**Comment by carlsverre** [comment]
Thanks for fixing this so quickly! :fire:
